[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "PSMC_Tutorial-BirdLab"
authors = [{name = "Vinay KL", email = "vkl1@lsu.edu"}]
dynamic = ["version", "description"]
